let meetingPartsById = {
    meetingPartsById: {
        "323": {
            "4": {
                id: 4,
                part_id: 4,
                start_time: "2019-01-23T19:30:00+11:00",
                minutes: 5,
                part_title: "Song {no} and Prayer",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3075,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: true,
                assistant: true,
                replace_token: "{no}",
                min_suffix: "min.",
                section_id: 4,
                sort_order: 10,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: "Prayer:",
                school_part: null,
                not_co_visit: null,
                partname: "Song {no} and Prayer",
                songNumber: null
            },
            "5": {
                id: 5,
                part_id: 5,
                start_time: "2019-01-23T19:35:00+11:00",
                minutes: 3,
                part_title: "Opening Comments — Chairman",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3076,
                active: true,
                chairman_part: true,
                co_visit: false,
                no_assign: false,
                assistant: false,
                replace_token: "",
                min_suffix: "min. or less",
                section_id: 4,
                sort_order: 20,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                partname: "Opening Comments — Chairman",
                songNumber: null
            },
            "6": {
                id: 6,
                part_id: 6,
                start_time: "2019-01-23T19:38:00+11:00",
                minutes: 10,
                part_title: "Treasures from God's Word",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3077,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: false,
                replace_token: "",
                min_suffix: "min.",
                section_id: 1,
                sort_order: 30,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                partname: "Treasures from God's Word",
                songNumber: null
            },
            "7": {
                id: 7,
                part_id: 7,
                start_time: "2019-01-23T19:48:00+11:00",
                minutes: 8,
                part_title: "Digging for Spiritual Gems",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3078,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: false,
                replace_token: "",
                min_suffix: "min.",
                section_id: 1,
                sort_order: 40,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                partname: "Digging for Spiritual Gems",
                songNumber: null
            },
            "12": {
                id: 12,
                part_id: 12,
                start_time: "2019-01-23T19:56:00+11:00",
                minutes: 5,
                part_title: "Song {no}",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3079,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: true,
                assistant: false,
                replace_token: "{no}",
                min_suffix: "min. or less",
                section_id: 3,
                sort_order: 130,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                partname: "Song {no}",
                songNumber: null
            },
            "13": {
                id: 13,
                part_id: 13,
                start_time: "2019-01-23T20:01:00+11:00",
                minutes: 15,
                part_title: "Living as Christians Part 1",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3080,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: false,
                replace_token: "",
                min_suffix: "min.",
                section_id: 3,
                sort_order: 140,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                partname: "Living as Christians Part 1",
                songNumber: "1"
            },
            "14": {
                id: 14,
                part_id: 14,
                start_time: "2019-01-23T20:16:00+11:00",
                minutes: 8,
                part_title: "Living as Christians Part 2",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3081,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: false,
                replace_token: "",
                min_suffix: "min. ",
                section_id: 3,
                sort_order: 150,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                partname: "Living as Christians Part 2",
                songNumber: "2"
            },
            "15": {
                id: 15,
                part_id: 15,
                start_time: "2019-01-23T20:24:00+11:00",
                minutes: 30,
                part_title: "Congregation Bible Study",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3082,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: true,
                replace_token: "",
                min_suffix: "min.",
                section_id: 3,
                sort_order: 160,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: "Reader:",
                school_part: false,
                not_co_visit: true,
                partname: "Congregation Bible Study",
                songNumber: null
            },
            "16": {
                id: 16,
                part_id: 16,
                start_time: "2019-01-23T20:54:00+11:00",
                minutes: 3,
                part_title: "Review Followed by Preview of Next Week",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3083,
                active: true,
                chairman_part: true,
                co_visit: false,
                no_assign: false,
                assistant: false,
                replace_token: "",
                min_suffix: "min. or less",
                section_id: 5,
                sort_order: 170,
                counsel_mins: 0,
                link_to: 5,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                partname: "Review Followed by Preview of Next Week",
                songNumber: null
            },
            "17": {
                id: 17,
                part_id: 17,
                start_time: "2019-01-23T20:57:00+11:00",
                minutes: 5,
                part_title: "Song {no} and Prayer",
                meeting_id: 323,
                person_id: null,
                assistant_id: null,
                aux_person_id: null,
                aux_assistant_id: null,
                assigned_id: 3084,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: true,
                assistant: true,
                replace_token: "{no}",
                min_suffix: "min.",
                section_id: 5,
                sort_order: 200,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: "Prayer:",
                school_part: null,
                not_co_visit: null,
                partname: "Song {no} and Prayer",
                songNumber: null
            }
        },
        "d9dd6e76-bfc7-4364-ac84-9e094c21b46a": {
            "4": {
                id: 4,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: true,
                assistant: true,
                partname: "Song {no} and Prayer",
                replace_token: "{no}",
                minutes: 5,
                start_time: "2019-01-23T19:30:00+11:00",
                min_suffix: "min.",
                section_id: 4,
                sort_order: 10,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: "Prayer:",
                school_part: null,
                not_co_visit: null,
                meeting_id: 324,
                assigned_id: 3085
            },
            "5": {
                id: 5,
                active: true,
                chairman_part: true,
                co_visit: false,
                no_assign: false,
                assistant: false,
                partname: "Opening Comments — Chairman",
                replace_token: "",
                minutes: 3,
                start_time: "2019-01-23T19:35:00+11:00",
                min_suffix: "min. or less",
                section_id: 4,
                sort_order: 20,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                meeting_id: 324,
                assigned_id: 3086
            },
            "6": {
                id: 6,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: false,
                partname: "Treasures from God's Word",
                replace_token: "",
                minutes: 10,
                start_time: "2019-01-23T19:38:00+11:00",
                min_suffix: "min.",
                section_id: 1,
                sort_order: 30,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                meeting_id: 324,
                assigned_id: 3087
            },
            "7": {
                id: 7,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: false,
                partname: "Digging for Spiritual Gems",
                replace_token: "",
                minutes: 8,
                start_time: "2019-01-23T19:48:00+11:00",
                min_suffix: "min.",
                section_id: 1,
                sort_order: 40,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                meeting_id: 324,
                assigned_id: 3088
            },
            "12": {
                id: 12,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: true,
                assistant: false,
                partname: "Song {no}",
                replace_token: "{no}",
                minutes: 5,
                start_time: "2019-01-23T19:56:00+11:00",
                min_suffix: "min. or less",
                section_id: 3,
                sort_order: 130,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                meeting_id: 324,
                assigned_id: 3089
            },
            "13": {
                id: 13,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: false,
                partname: "Living as Christians Part 1",
                replace_token: "",
                minutes: 15,
                start_time: "2019-01-23T20:01:00+11:00",
                min_suffix: "min.",
                section_id: 3,
                sort_order: 140,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                meeting_id: 324,
                assigned_id: 3090
            },
            "14": {
                id: 14,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: false,
                partname: "Living as Christians Part 2",
                replace_token: "",
                minutes: 8,
                start_time: "2019-01-23T20:16:00+11:00",
                min_suffix: "min. ",
                section_id: 3,
                sort_order: 150,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                meeting_id: 324,
                assigned_id: 3091
            },
            "15": {
                id: 15,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: false,
                assistant: true,
                partname: "Congregation Bible Study",
                replace_token: "",
                minutes: 30,
                start_time: "2019-01-23T20:24:00+11:00",
                min_suffix: "min.",
                section_id: 3,
                sort_order: 160,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: "Reader:",
                school_part: false,
                not_co_visit: true,
                meeting_id: 324,
                assigned_id: 3092
            },
            "16": {
                id: 16,
                active: true,
                chairman_part: true,
                co_visit: false,
                no_assign: false,
                assistant: false,
                partname: "Review Followed by Preview of Next Week",
                replace_token: "",
                minutes: 3,
                start_time: "2019-01-23T20:54:00+11:00",
                min_suffix: "min. or less",
                section_id: 5,
                sort_order: 170,
                counsel_mins: 0,
                link_to: 5,
                has_auxiliary: false,
                assistant_prefix: null,
                school_part: null,
                not_co_visit: null,
                meeting_id: 324,
                assigned_id: 3093
            },
            "17": {
                id: 17,
                active: true,
                chairman_part: false,
                co_visit: false,
                no_assign: true,
                assistant: true,
                partname: "Song {no} and Prayer",
                replace_token: "{no}",
                minutes: 5,
                start_time: "2019-01-23T20:57:00+11:00",
                min_suffix: "min.",
                section_id: 5,
                sort_order: 200,
                counsel_mins: 0,
                link_to: null,
                has_auxiliary: false,
                assistant_prefix: "Prayer:",
                school_part: null,
                not_co_visit: null,
                meeting_id: 324,
                assigned_id: 3094
            }
        }
    }
};

const newMeetingPartsById = { ...meetingPartsById.meetingPartsById }

console.log(meetingPartsById.meetingPartsById === meetingPartsById.meetingPartsById)
console.log(newMeetingPartsById === meetingPartsById.meetingPartsById)
const mp = "323"
const pid = "4"
console.log()
console.log("checking sub components", newMeetingPartsById[mp][pid] === meetingPartsById.meetingPartsById[mp][pid])

console.log(JSON.parse(JSON.stringify(newMeetingPartsById)) === meetingPartsById.meetingPartsById)

const mpbid = meetingPartsById.meetingPartsById;

const ret = {
    ...mpbid,
    [mp]: {
        ...mpbid[mp],
        [pid]: {
            ...mpbid[mp][pid],
            horribleDepth: 1
        }
    },

}

console.log(ret)
